### PR TITLE
ios11-fixes (tested only with NEO.emu and MD.emu)

### PR DESCRIPTION
**Pull request by palla89**
- FileUtils.cc in EmuFramework: changed ‘system’ function not available anymore, with ‘nftw’ function
- iphone.mm in Imagine: forced folder to Documents for non-jailbreak users
- NEO.emu and MD.emu build files changed to compile only for 64bit processors (iOS 11 now permits only 64 bit apps)
- MDFNApi.cc in PCE.emu folder: commented two functions that were giving error when compiling for MD.emu and aren’t used (not the best solution but I don’t have a full understanding of the project, any help appreciated)

### CODE REVIEW

**Comment by Rakashazi** [comment]
Hi, I replaced system() with a similar implementation using posix_spawn() that compiles with the latest Xcode. As for your other changes I'm working on improving how the documents directory is handled and it should be updated in the next couple commits.

**Comment by palla89** [comment]
That's awesome! Not sure if this is the right place, but when running on iPhone, if I put it into landscape mode, the view will rotate on itself in a wrong way, cropping everything. If you want to check it out too, that would be awesome :)

**Comment by bitmst** [comment]
I can try out snes9x for you if you want

**Comment by bitmst** [comment]
I am on an Android Samsung Galaxy a 50

**Comment by bladeoner** [comment]
@palla89 > That's awesome! Not sure if this is the right place, but when running on iPhone, if I put it into landscape mode, the view will rotate on itself in a wrong way, cropping everything. If you want to check it out too, that would be awesome :)

Is the issue you described still in the current version?

**Pull request closed without merging**
